### ISSUE TITLE
Error: File `rds-regexchange.pdf' not found

### ISSUE THREAD

**Issue by alschmid** [msdemlei/dig-um-fi-init#2]
Hallo,
soll das repository eigentlich compilieren? Mindestens eine figure scheint nicht vorhanden zu sein:

Error: File `rds-regexchange.pdf' not found

Grüsse, 
A. S.

**Comment by msdemlei** [comment]
On Thu, Jan 13, 2022 at 07:11:24AM -0800, alschmid wrote:
> Hallo,
> soll das repository eigentlich compilieren? Mindestens eine figure scheint nicht vorhanden zu sein:
> 
> Error: File `rds-regexchange.pdf' not found

Oh.  Das ist der Fluch von Abbildungen mit der Erweiterung .pdf:
.gitignore frisst sie.

Ich habe die Datei eben noch gepusht -- danke für den Hinweis.

**Comment by alschmid** [comment]
danke, jetzt ist die Grafik da
